#!/bin/bash

log_options='--pretty="format:- %s" -i --grep="^add" --grep="^fix" --grep="^remove" --grep="^update"'

if [ -z "$1" ]; then
	eval "git log ${log_options} -50"
elif [ "$1" == "-a" ]; then
	eval "git log ${log_options}"
elif [ "$1" == "-tag" ]; then
	#Get and print the name of the last tag
	IFS='...' read -ra tag_range <<< "$2"
	last_tag_index=${#tag_range[@]}-1
	printf "## ${tag_range[$last_tag_index]}\n\n"

	#Get and print the latest commit date
	log_date="$(git log --pretty="format:%cd" --date="format:%b. %d, %Y" -1 $2)"
	printf "*$log_date*\n\n"

	#Print the changelog
	eval "git log ${log_options} $2"
else
	eval "git log --since=\"$1\" ${log_options}"
fi

echo ""
